# Generated by Django 6.0.7 on 2026-07-15 15:14

import gallery.models
import gallery.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title/description for the image.', max_length=255)),
                ('image', models.ImageField(help_text='Accepted formats: JPG, JPEG, PNG, GIF. Max size: 10 MB.', upload_to=gallery.models.upload_to_gallery, validators=[gallery.validators.validate_image_extension, gallery.validators.validate_image_mime_type, gallery.validators.validate_image_size])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
